{config, lib, ...}:

{
  imports = [
  ];
  wayland.windowManager.hyprland = {
    enable = true;
    configType = "lua";

    extraLuaFiles = {
      "default.keybinds" = {
        content = ./keybinds.lua;
        autoLoad = true;
      };
    };
    extraLuaFiles = {
      "default.general" = {
        content = ./general.lua;
        autoLoad = true;
      };
    };
    extraLuaFiles = {
      "default.env" = {
        content = ./env.lua;
        autoLoad = true;
      };
    };
    extraLuaFiles = {
      "default.execs" = {
        content = ./execs.lua;
        autoLoad = true;
      };
    };

    
    extraConfig = ''
      -- These files where generated by NixOS
    '';
  };
} 
